export const PHOTOS_LOADING = 'PHOTOS_LOADING';
export const LOAD_PHOTOS = 'LOAD_PHOTOS';
export const PHOTOS_FAILED = 'PHOTOS_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT="UPDATE_COMMENT";

export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const COMMENT_LOADING = ' COMMENT_LOADING';